spring.application.name=ParkNet
debug=false
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

spring.datasource.url=jdbc:h2:mem:parknet;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
parknet.upload.base-dir=uploads
parknet.upload.listings-dir=uploads/listings

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
